version: '3'

services:
  # A local instance of dynamodb, which persists data between instances
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    container_name: dynamodb
    ports:
      # map port 8000 in the container to port 8000 in the host
      - "8000:8000"
    # tell dynamo to persist data  
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    # map a directory in the host OS to this container
    volumes:
     - ./data/dynamodb:/home/dynamodblocal/data      
  # The therapy service
  therapy:
    build: therapy-normalization
    hostname: therapy
    container_name: therapy
    environment: 
      - THERAPY_NORM_DB_URL=http://dynamodb:8000
      - AWS_DEFAULT_REGION=dev
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    ports:
      # map port 80 in the container to port 8001 in the host
      - "8001:80"
    depends_on:
      - "dynamodb"  


      